exports.phones = {
    samsung: [
        {
            id: 1,
            name: "Samsung Galaxy M53",
            description: `
            Released 2022 April 22 176g,,
            7.4mm thickness,
            Android 12,
            One UI 4.1,
            128GB/256GB storage, 
            1080x2408 pixels
            108MP,
            2160p,
            6/8GB RAM,
            Dimensity 900,
            5000mAh
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-m53-5g-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-m53-5g-2.jpg",
            ],
        },
        {
            id: 2,
            name: "Samsung Galaxy S20 FE 2022",
            description: `
            Released 2022 April 01,,
            190g,
            8.4mm thickness,
            Android 12,
            One UI 4.1,
            128GB storage,
            1080x2400 pixels,
            12MP,
            2160p,
            6GB RAM,
            Snapdragon 865 5G,
            4500mAh Li-Ion
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s20-fe-5g-1.jpg",
            ],
        },
        {
            id: 3,
            name: "Samsung Galaxy A73 5G",
            description: `
            Released 2022 April 22,,
            181g, 
            7.6mm thickness,
            Android 12, 
            One UI 4.1,
            128GB/256GB storage, 
            1080x2400 pixels,
            108MP,
            2160p,
            6/8GB RAM,
            Snapdragon 778G 5G,
            5000mAh Li-Po
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a73-5g-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a73-5g-2.jpg",
            ],
        },
        {
            id: 4,
            name: "Samsung Galaxy A53 5G",
            description: `
            Released 2022 March 24,
            189g, 
            8.1mm thickness,
            Android 12, 
            One UI 4.1,
            128GB/256GB storage,
            1080x2400 pixels,
            48MP,
            2160p,
            4-8GB RAM,
            5000mAh Li-Po
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a53-5g-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a33-5g-3.jpg",
            ],
        },
        {
            id: 5,
            name: "Samsung Galaxy A03",
            description: `
            Released 2022 January 21,,
            196g, 
            9.1mm thickness,
            Android 11,
            32GB/64GB/128GB storage,
            720x1600 pixels,
            48MP,
            1080p,
            3/4GB RAM,
            5000mAh Li-Po
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a03-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a03-2.jpg",
            ],
        },
        {
            id: 6,
            name: "Samsung Galaxy A13 5G",
            description: `
            Released 2021 December 03,,
            195g,
            8.8mm thickness,
            Android 11, 
            One UI,
            64GB storage,
            720x1600 pixels,
            50MP,
            1080p,
            4GB RAM,
            5000mAh Li-Po
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a13-5g-1.jpg",
            ],
        },
        {
            id: 7,
            name: "Samsung Galaxy Tab A8 10.5 (2021)",
            description: `
            Released 2022 January 17,,
            508g,
            6.9mm thickness,
            Android 11,
            One UI 3,
            32GB/64GB/128GB storage,
            1200x1920 pixels,
            8MP,
            1080p,
            3/4GB RAM,
            7040mAh Li-Po
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-a8-105-2021-0.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-a8-105-2021-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-a8-105-2021-2.jpg",
            ],
        },
        {
            id: 8,
            name: "Samsung Galaxy S21 FE 5G",
            description: `
            Released 2022 January 07,
            177g,
            7.9mm thickness
            Android 12,
            One UI 4
            128GB/256GB storage,
            1080x2400 pixels,
            12MP,
            2160p,
            6/8GB RAM,
            Snapdragon 888 5G,
            4500mAh Li-Ion
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s21-fe-5g-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s21-fe-5g-2.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s21-fe-5g-3.jpg",
            ],
        },
        {
            id: 9,
            name: "Samsung Galaxy Tab S8",
            description: `
            Released 2022 March 22,
            503g (Wi-Fi), 
            507g (5G), 
            6.3mm thickness
            Android 12,
            One UI 4.1
            128GB/256GB storage,
            1600x2560 pixels
            13MP
            2160p
            8/12GB RAM
            Snapdragon 8 Gen 1
            8000mAh Li-Po
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-s8-3.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-s8-4.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-s8-5.jpg",
            ],
        },
        {
            id: 10,
            name: "Samsung Galaxy Tab S8+",
            description: `
            Released 2022 April 14,
            567g (Wi-Fi), 
            572g (5G), 
            5.7mm thickness
            Android 12, One UI 4.1
            128GB/256GB storage,
            1752x2800 pixels,
            13MP,
            2160p,
            8/12GB RAM,
            Snapdragon 8 Gen 1,
            10090mAh Li-Po
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-s8-plus-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-s8-plus-2.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-s8-plus-3.jpg",
            ],
        },
        {
            id: 11,
            name: "Samsung Galaxy Tab S8 Ultra",
            description: `
            Exp. release 2022 April
            726g (Wi-Fi),
            728g (5G),
            5.5mm thickness,
            Android 12, One UI 4.1,
            128GB/256GB/512GB storage,
            1848x2960 pixels,
            13MP,
            2160p,
            8-16GB RAM,
            Snapdragon 8 Gen 1,
            11200mAh Li-Po
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-s8-ultra-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-s8-ultra-2.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-s8-ultra-3.jpg",
            ],
        },
        {
            id: 12,
            name: "Samsung Galaxy S22 5G",
            description: `
            Released 2022 February 25,
            167g / 168g (mmWave),
            7.6mm thickness,
            Android 12,,
            One UI 4.1,
            128GB/256GB storage,,
            1080x2340 pixels,
            50MP,
            4320p,
            8GB RAM,
            3700mAh
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-5g-2.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-5g-3.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-5g-4.jpg",
            ],
        },
        {
            id: 13,
            name: "Samsung Galaxy S22+ 5G",
            description: `
            Released 2022 February 25,
            195g / 196g (mmWave), ,
            7.6mm thickness,
            Android 12, ,
            One UI 4.1,
            128GB/256GB storage,,
            1080x2340 pixels,
            50MP,
            4320p,
            8GB RAM,
            4500mAh Li-Ion
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-plus-5g-2.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-plus-5g-3.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-5g-4.jpg",
            ],
        },
        {
            id: 14,
            name: "Samsung Galaxy S22 Ultra 5G",
            description: `
            Released 2022 February 25,
            228g / 229g (mmWave), ,
            8.9mm thickness,
            Android 12, ,
            One UI 4.1,
            1440x3088 pixels,
            108MP,
            4320p,
            8/12GB RAM,
            Exynos 2200,
            5000mAh
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-ultra-5g-2.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-ultra-5g-3.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-ultra-5g-6.jpg",
            ],
        },
        {
            id: 15,
            name: "Samsung Galaxy A13 pictures",
            description: `
            Released 2022 March 23,
            195g,
            8.8mm thickness,
            Android 12,
            One UI 4.1,
            1080x2408 pixels,
            50MP,
            1080p,
            3-6GB RAM,
            Exynos 850,
            5000mAh Li-Po
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a13-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a13-2.jpg",
            ],
        },
        {
            id: 16,
            name: "Samsung Galaxy A23",
            description: `
            Released 2022 March 25,
            195g,
            8.4mm thickness,
            Android 12,
            One UI 4.1,
            64GB/128GB storage,
            1080x2408 pixels,
            50MP,
            1080p,
            4-8GB RAM,
            Snapdragon 665,
            5000mAh Li-Po
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a23-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a23-2.jpg",
            ],
        },
    ],
    apple: [
        {
            id: 1,
            name: "Apple iPhone 12 Pro Max",
            description: `
            Released 2020, November 13,
            228g,
            7.4mm thickness,
            iOS 14.1, up to iOS 15.4.1,
            128GB/256GB/512GB storage,
            1284x2778 pixels,
            12MP,
            2160p,
            6GB RAM,
            Apple A14 Bionic,
            3687mAh Li-Ion
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-pro-max-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-pro-max-4.jpg",
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-pro-max-3.jpg",
            ],
        },
        {
            id: 2,
            name: "Apple iPhone XS Max",
            description: `
            Released 2018, September 21,
            208g,
            7.7mm thickness,
            iOS 12, up to iOS 15.4.1,
            64GB/256GB/512GB storage,
            1242x2688 pixels,
            12MP,
            2160p,
            4GB RAM,
            Apple A12 Bionic,
            3174mAh
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-xs-max-5.jpg",
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-xs-max-3.jpg",
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-xs-max-4.jpg",
            ],
        },
        {
            id: 3,
            name: "Apple iPhone SE (2020)",
            description: `
            Released 2020, April 24,
            148g, ,
            7.3mm thickness,
            iOS 13, up to iOS 15.4.1,
            64GB/128GB/256GB storage,
            750x1334 pixels,
            12MP,
            2160p,
            3GB RAM,
            Apple A13 Bionic,
            1821mAh
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-se-2020-2.jpg",
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-se-2020-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-se-2020-3.jpg",
            ],
        },
        {
            id: 4,
            name: "Apple iPhone 12",
            description: `
            Released 2020, October 23,
            164g, 7.4mm thickness,
            iOS 14.1, up to iOS 15.4.1,
            64GB/128GB/256GB storage,
            1170x2532 pixels,
            12MP,
            2160p,
            4GB RAM,
            Apple A14 Bionic,
            2815mAh Li-Ion
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-r1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-2.jpg",
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-3.jpg",
            ],
        },
        {
            id: 5,
            name: "Apple iPhone 13 mini",
            description: `
            Released 2021, September 24,
            141g, 7.7mm thickness,
            iOS 15, up to iOS 15.4.1,
            128GB/256GB/512GB storage,
            1080x2340 pixels,
            12MP,
            2160p,
            4GB RAM,
            Apple A15 Bionic,
            2438mAh
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-mini-01.jpg",
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-mini-2.jpg",
                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-3.jpg",
            ],
        },
    ],
    redmi: [
        {
            id: 1,
            name: "Xiaomi Redmi Note 11S 5G",
            description: `
            Release 2022 April,
            195g,
            8.8mm thickness,
            Android 11,
            MIUI 13,
            64GB/128GB storage,
            1080x2400 pixels,
            50MP,
            1080p,
            4/6GB RAM,
            Dimensity 810,
            5000mAh
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-redmi-note-11s-5g-02.jpg",
                "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-redmi-note-11s-5g-05.jpg",
                "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-redmi-note-11s-5g-04.jpg",
            ],
        },
        {
            id: 2,
            name: "Xiaomi Redmi 10A",
            description: `
            Released 2022 March 31,
            194g,
            9mm thickness,
            Android 11,
            MIUI 12.5,
            32GB/64GB/128GB storage,
            720x1600 pixels,
            13MP,
            1080p,
            3-6GB RAM,
            Helio G25,
            5000mAh
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-redmi-10a-2.jpg",
                "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-redmi-10a-1.jpg",
            ],
        },
        {
            id: 3,
            name: "Xiaomi Black Shark 5 Pro",
            description: `
            Released 2022 April 04,
            220g,
            9.5mm thickness,
            Android 12,
            Joy UI 13,
            256GB/512GB storage,
            1080x2400 pixels,
            108MP,
            2160p,
            8-16GB RAM,
            Snapdragon 8 Gen 1,
            4650mAh
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-black-shark-5-pro-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-black-shark-5-pro-2.jpg",
            ],
        },
        {
            id: 4,
            name: "Xiaomi Poco F4 GT",
            description: `
            Released 2022 April 28,
            210g, 8.5mm thickness,
            Android 12, MIUI 13,
            128GB/256GB storage,
            1080x2400 pixels,
            64MP,
            2160p,
            8/12GB RAM,
            Snapdragon 8 Gen 1,
            4700mAh
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-poco-f4-gt-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-poco-f4-gt-05.jpg",
            ],
        },
        {
            id: 5,
            name: "Xiaomi Poco M4 5G",
            description: `
            Release 2022 May 05,
            200g, 8.9mm thickness,
            Android 12, MIUI 13,
            64GB/128GB storage,
            1080x2400 pixels,
            50MP,
            1080p,
            4/6GB RAM,
            Dimensity 700,
            5000mAh
        `,
            images: [
                "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-poco-m4-5g-1.jpg",
                "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-poco-m4-5g-2.jpg",
            ],
        },
    ],
};

exports.supplierNames = [
    "Danit Creboe",
    "Corette Gippes",
    "Ashlie Tomson",
    "Kayla Adlard",
    "Boycie Duligall",
    "Alfy Demann",
    "Kial Doore",
    "Joelle Lowmass",
    "Robin Finding",
    "Barbee Sausman",
    "Madelyn Orring",
    "Archambault Demangel",
    "Torrie Charopen",
    "Luz Sinson",
    "Robena Mitchelhill",
    "Pru Pabst",
    "Lurette Van der Brugge",
    "Cully Amis",
    "Berenice Branston",
    "Christy Quemby",
    "Kerry Knottley",
    "Skip Bainbridge",
    "Marlowe Eddison",
    "Elisabet Gauge",
    "Pren Giraldo",
    "Ramon Palleske",
    "Renaldo Michele",
    "Ebeneser Petschelt",
    "Hettie Naton",
    "Ingamar Zecchinelli",
    "Godard Birden",
    "Gerrilee Fitzsimmons",
    "Clint Matveyev",
    "Fabiano Spawton",
    "Audie Slatter",
    "Amelita Ivashkin",
    "Suellen Waterstone",
    "Darrick Baddam",
    "Kelsi Cuttles",
    "Tim Speight",
    "Olimpia Pooly",
    "Leona Teliga",
    "Ivett Nethercott",
    "Othelia Whanstall",
    "Mendy Outerbridge",
    "Anatole Greatbanks",
    "Dimitry Delwater",
    "Hale Danielski",
    "Guy Alston",
    "Inglis Baison",
    "Toinette Sparrowe",
    "Illa Glandfield",
    "Francklin Stobbart",
    "Doroteya Prantoni",
    "Brocky Skupinski",
    "Ruttger Folland",
    "Brig Janacek",
    "Florenza Baszniak",
    "Elise Topaz",
    "Audrye Double",
    "Wylie Hatje",
    "Emmery Gherardelli",
    "Fanni Cuxon",
    "Livvyy Dooley",
    "Rosene Springell",
    "Marrissa Seawright",
    "Christophe Stockwell",
    "Fabian Shayler",
    "Booth Gibard",
    "Clerissa Vennart",
    "Noellyn Mounfield",
    "Pearla Adamovitch",
    "Marya De Simoni",
    "Lucias Ygou",
    "Vale Petegrew",
    "Upton Vowdon",
    "Winfield Leaburn",
    "Linzy Teager",
    "Westley Rubertelli",
    "Benito Stilwell",
    "Fawnia Griffiths",
    "Ema Geane",
    "Danika Trustrie",
    "Shay Caile",
    "Karalynn Crighton",
    "Barri Fobidge",
    "Claiborn Polotti",
    "Josee Jobey",
    "Franchot Grunwald",
    "Rafaelia Pithcock",
    "Sanson Adolf",
    "Mayne Pariss",
    "Lazaro Kruse",
    "Marj Gallager",
    "Almeda Chedgey",
    "Keslie Swale",
    "Paige Huonic",
    "Jorge Strutt",
    "Renato Grute",
    "Maurine Gibbonson",
];
